### PR TITLE
convert pandas object

### PR DESCRIPTION
**Pull request by Genie-Liu**
I find that the fit method convert pandas object but predict does not.

### CODE REVIEW

**Comment by Genie-Liu** [comment]
or we can move this convertion to _split_num_cat function

**Comment by nicodv** [comment]
Can't believe I missed that. Thanks for the PR, @Genie-Liu !

If you could add the same line in `kmodes.py` too, that would be great.

**Comment by Genie-Liu** [comment]
> Can't believe I missed that. Thanks for the PR, @Genie-Liu !
> 
> If you could add the same line in `kmodes.py` too, that would be great.

Added!

**Comment by nicodv** [comment]
Please address the 2 minor issues that Codacy points out (https://app.codacy.com/app/nicodv/kmodes/pullRequest?prid=3427689), @Genie-Liu , then I'll merge this.

**Comment by Genie-Liu** [comment]
> Please address the 2 minor issues that Codacy points out (https://app.codacy.com/app/nicodv/kmodes/pullRequest?prid=3427689), @Genie-Liu , then I'll merge this.

OK~

**Comment by nicodv** [comment]
Merged. Thanks again, @Genie-Liu .

**Pull request merged**
